import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '2026.7.1:0',
  releaseNotes: {
    en_US:
      'Updated Hermes Agent to 2026.7.1 (the Judgment Release). Highlights: Mixture-of-Agents is now a first-class, selectable model, with each reference model’s reasoning shown and the aggregator’s answer streamed live; the agent now verifies its own work against evidence and /goal gained completion contracts; new /learn and /journey self-improvement tooling and a playable memory graph; background subagent fan-out; gateway scale-to-zero and drain coordination; and a security round hardening credential-exfil surfaces. Upstream also closed 100% of its P0/P1 backlog. Full notes: https://github.com/NousResearch/hermes-agent/releases/tag/v2026.7.1. Also fixes recurring OAuth/Nous token-refresh drops: the provider and gateway health checks now run as the Hermes service user (uid 1000) instead of root, so they can no longer leave auth-store files root-owned and lock the gateway out of refreshing its short-lived access token. Existing installs are repaired automatically on upgrade.',
    es_ES:
      'Se actualizó Hermes Agent a 2026.7.1 (the Judgment Release). Novedades: Mixture-of-Agents ahora es un modelo seleccionable de primera clase, mostrando el razonamiento de cada modelo de referencia y transmitiendo en vivo la respuesta del agregador; el agente ahora verifica su propio trabajo con evidencia y /goal incorpora contratos de finalización; nuevas herramientas de automejora /learn y /journey y un grafo de memoria interactivo; ejecución en segundo plano de subagentes en paralelo; escalado a cero y coordinación de drenaje en el gateway; y una ronda de seguridad que refuerza las superficies de exfiltración de credenciales. Upstream también cerró el 100% de su backlog P0/P1. Notas completas: https://github.com/NousResearch/hermes-agent/releases/tag/v2026.7.1. También corrige las caídas recurrentes de la actualización del token OAuth/Nous: las comprobaciones de estado del proveedor y de la puerta de enlace ahora se ejecutan como el usuario del servicio Hermes (uid 1000) en lugar de root, por lo que ya no pueden dejar los archivos del almacén de autenticación propiedad de root ni impedir que la puerta de enlace renueve su token de acceso de corta duración. Las instalaciones existentes se reparan automáticamente al actualizar.',
    de_DE:
      'Hermes Agent auf 2026.7.1 aktualisiert (the Judgment Release). Highlights: Mixture-of-Agents ist jetzt ein erstklassiges, auswählbares Modell – die Argumentation jedes Referenzmodells wird angezeigt und die Antwort des Aggregators live gestreamt; der Agent überprüft seine eigene Arbeit nun anhand von Belegen und /goal erhielt Abschlussverträge; neue Selbstverbesserungs-Tools /learn und /journey sowie ein interaktiver Speichergraph; Hintergrund-Fan-out von Subagenten; Scale-to-Zero und Drain-Koordination im Gateway; und eine Sicherheitsrunde, die Angriffsflächen zur Exfiltration von Anmeldedaten härtet. Upstream schloss zudem 100% seines P0/P1-Backlogs. Vollständige Hinweise: https://github.com/NousResearch/hermes-agent/releases/tag/v2026.7.1. Behebt außerdem wiederkehrende Abbrüche der OAuth/Nous-Token-Aktualisierung: Die Health-Checks für Anbieter und Gateway laufen jetzt als Hermes-Dienstbenutzer (uid 1000) statt als root, sodass sie die Dateien des Auth-Speichers nicht mehr root-eigen zurücklassen und das Gateway nicht mehr daran hindern können, sein kurzlebiges Zugriffstoken zu erneuern. Bestehende Installationen werden beim Upgrade automatisch repariert.',
    pl_PL:
      'Zaktualizowano Hermes Agent do 2026.7.1 (the Judgment Release). Najważniejsze zmiany: Mixture-of-Agents jest teraz pełnoprawnym, wybieralnym modelem – pokazywane jest rozumowanie każdego modelu referencyjnego, a odpowiedź agregatora jest transmitowana na żywo; agent weryfikuje własną pracę na podstawie dowodów, a /goal zyskał kontrakty ukończenia; nowe narzędzia samodoskonalenia /learn i /journey oraz interaktywny graf pamięci; równoległe uruchamianie podagentów w tle; skalowanie do zera i koordynacja opróżniania w bramie; oraz runda bezpieczeństwa wzmacniająca powierzchnie wycieku poświadczeń. Upstream zamknął też 100% swojego backlogu P0/P1. Pełne informacje: https://github.com/NousResearch/hermes-agent/releases/tag/v2026.7.1. Naprawia też powracające przerwy w odświeżaniu tokena OAuth/Nous: testy stanu dostawcy i bramy działają teraz jako użytkownik usługi Hermes (uid 1000) zamiast root, dzięki czemu nie mogą już pozostawiać plików magazynu uwierzytelniania jako własność root ani blokować bramie odświeżania krótkotrwałego tokena dostępu. Istniejące instalacje są naprawiane automatycznie podczas aktualizacji.',
    fr_FR:
      'Hermes Agent mis à jour vers 2026.7.1 (the Judgment Release). Nouveautés : Mixture-of-Agents est désormais un modèle sélectionnable à part entière – le raisonnement de chaque modèle de référence est affiché et la réponse de l’agrégateur est diffusée en direct ; l’agent vérifie maintenant son propre travail à partir de preuves et /goal a gagné des contrats d’achèvement ; nouveaux outils d’auto-amélioration /learn et /journey et un graphe de mémoire interactif ; exécution en arrière-plan de sous-agents en parallèle ; mise à l’échelle à zéro et coordination du drainage dans la passerelle ; et une série de correctifs de sécurité renforçant les surfaces d’exfiltration d’identifiants. Upstream a également clôturé 100% de son backlog P0/P1. Notes complètes : https://github.com/NousResearch/hermes-agent/releases/tag/v2026.7.1. Corrige également les interruptions récurrentes du rafraîchissement du jeton OAuth/Nous : les vérifications d’état du fournisseur et de la passerelle s’exécutent désormais en tant qu’utilisateur du service Hermes (uid 1000) au lieu de root, de sorte qu’elles ne peuvent plus laisser les fichiers du magasin d’authentification appartenant à root ni empêcher la passerelle de renouveler son jeton d’accès de courte durée. Les installations existantes sont réparées automatiquement lors de la mise à jour.',
  },
  migrations: {
    up: async ({ effects }) => {},
    down: IMPOSSIBLE,
  },
})
